apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "finops360-k8s-collector.prometheus.server.labels" . | nindent 4 }}
  name: prometheus-server-password-secret
{{ include "finops360-k8s-collector.prometheus.namespace" . | indent 2 }}
type: Opaque
stringData:
  passwd: |
    {{ required "prometheus.server.password is required" .Values.prometheus.server.password }}
